"""
daily_briefing.py

Generates a personalised morning briefing for the authenticated client and
delivers it via the Resend transactional email API.

Called every weekday morning at 07:45 by the daily-briefing n8n workflow
(POST /briefing/generate-and-send — admin-only endpoint in main.py).

The briefing covers:
  1. Inbox health snapshot — reputation scores, paused inboxes, any auto-pauses
  2. Campaign performance — top 3 by reply rate, any with bounce rate > 3%
  3. Active experiments — status, progress toward min_sample_size
  4. Pending decisions — entries in decision_log with effect IS NULL (unevaluated)
  5. AI-generated focus — one short paragraph from Claude Sonnet with the most
     important thing to act on today, written in Dutch.

The briefing is sent as an HTML email via Resend.  If RESEND_API_KEY is not
configured, the HTML is returned as a string (useful for local testing).

Environment variables:
    SUPABASE_URL, SUPABASE_KEY       — required
    ANTHROPIC_API_KEY                — required (Claude Sonnet for focus block)
    RESEND_API_KEY                   — required for email delivery; optional for dry-run
    BRIEFING_FROM_EMAIL              — sender address (default: briefing@meet-aerys.nl)
    BRIEFING_TO_EMAIL                — override recipient (default: client's own email)
    WARMUP_LANGUAGE                  — nl | en | fr (default: nl)
"""
from __future__ import annotations

import logging
import os
from datetime import date, datetime, timedelta, timezone
from typing import Optional

import httpx
from anthropic import Anthropic
from dotenv import load_dotenv
from supabase import Client, create_client

load_dotenv()

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
_SUPABASE_URL: str = os.getenv("SUPABASE_URL", "")
_SUPABASE_KEY: str = os.getenv("SUPABASE_KEY", "")
_ANTHROPIC_KEY: str = os.getenv("ANTHROPIC_API_KEY", "")
_RESEND_KEY: str = os.getenv("RESEND_API_KEY", "")
_FROM_EMAIL: str = os.getenv("BRIEFING_FROM_EMAIL", "briefing@meet-aerys.nl")
_LANGUAGE: str = os.getenv("WARMUP_LANGUAGE", "nl")

_LANG_LABELS: dict[str, dict[str, str]] = {
    "nl": {
        "subject": "Warmr dagelijkse briefing",
        "greeting": "Goedemorgen",
        "inbox_section": "Inbox gezondheid",
        "campaign_section": "Campagne prestaties",
        "experiment_section": "Actieve experimenten",
        "decision_section": "Openstaande beslissingen",
        "focus_section": "Focuspunt van vandaag",
        "ready": "klaar",
        "warmup": "opwarmen",
        "paused": "gepauzeerd",
        "no_campaigns": "Geen actieve campagnes.",
        "no_experiments": "Geen actieve experimenten.",
        "no_decisions": "Geen openstaande beslissingen.",
        "reply_rate": "Reply rate",
        "bounce_rate": "Bounce rate",
        "progress": "voortgang",
        "footer": "Dit is een automatisch gegenereerde briefing door Warmr.",
    },
    "en": {
        "subject": "Warmr daily briefing",
        "greeting": "Good morning",
        "inbox_section": "Inbox health",
        "campaign_section": "Campaign performance",
        "experiment_section": "Active experiments",
        "decision_section": "Pending decisions",
        "focus_section": "Today's focus",
        "ready": "ready",
        "warmup": "warming up",
        "paused": "paused",
        "no_campaigns": "No active campaigns.",
        "no_experiments": "No active experiments.",
        "no_decisions": "No pending decisions.",
        "reply_rate": "Reply rate",
        "bounce_rate": "Bounce rate",
        "progress": "progress",
        "footer": "This briefing was automatically generated by Warmr.",
    },
}

_L = _LANG_LABELS.get(_LANGUAGE, _LANG_LABELS["nl"])


# ---------------------------------------------------------------------------
# Data gathering
# ---------------------------------------------------------------------------

def _gather_inbox_data(sb: Client, client_id: str) -> dict:
    """Return inbox health summary for the client."""
    resp = (
        sb.table("inboxes")
        .select("email, reputation_score, status, warmup_active, spam_complaints, daily_sent")
        .eq("client_id", client_id)
        .execute()
    )
    inboxes = resp.data or []
    ready = [i for i in inboxes if i["status"] == "ready"]
    warming = [i for i in inboxes if i["status"] == "warmup"]
    paused = [i for i in inboxes if not i.get("warmup_active") or i["status"] == "paused"]
    avg_rep = round(sum(i.get("reputation_score", 0) for i in inboxes) / len(inboxes), 1) if inboxes else 0
    complaints_today = sum(i.get("spam_complaints", 0) for i in inboxes)

    return {
        "total": len(inboxes),
        "ready": len(ready),
        "warming": len(warming),
        "paused": len(paused),
        "avg_reputation": avg_rep,
        "spam_complaints": complaints_today,
        "rows": inboxes,
    }


def _gather_campaign_data(sb: Client, client_id: str) -> list[dict]:
    """Return top 5 campaigns by reply rate with basic stats."""
    # Get active campaigns
    camp_resp = (
        sb.table("campaigns")
        .select("id, name, status, total_leads")
        .eq("client_id", client_id)
        .in_("status", ["active", "sending"])
        .order("created_at", desc=True)
        .limit(10)
        .execute()
    )
    campaigns = camp_resp.data or []
    if not campaigns:
        return []

    since = (datetime.now(timezone.utc) - timedelta(days=7)).isoformat()
    results = []
    for c in campaigns:
        sched_resp = (
            sb.table("sending_schedule")
            .select("status")
            .eq("campaign_id", c["id"])
            .gte("sent_at", since)
            .execute()
        )
        rows = sched_resp.data or []
        sent = sum(1 for r in rows if r["status"] in ("sent", "replied", "bounced"))
        replied = sum(1 for r in rows if r["status"] == "replied")
        bounced = sum(1 for r in rows if r["status"] == "bounced")
        reply_rate = round(replied / sent * 100, 1) if sent else 0
        bounce_rate = round(bounced / sent * 100, 1) if sent else 0
        results.append({
            "name": c["name"],
            "status": c["status"],
            "sent_7d": sent,
            "reply_rate": reply_rate,
            "bounce_rate": bounce_rate,
            "alert": bounce_rate > 3,
        })

    results.sort(key=lambda x: x["reply_rate"], reverse=True)
    return results[:5]


def _gather_experiment_data(sb: Client, client_id: str) -> list[dict]:
    """Return active experiments with progress toward min_sample_size."""
    resp = (
        sb.table("experiments")
        .select("id, name, hypothesis, metric, min_sample_size, status, started_at, control_campaign_id, variant_campaign_id")
        .eq("client_id", client_id)
        .eq("status", "active")
        .execute()
    )
    experiments = resp.data or []
    results = []
    for exp in experiments:
        # Count sends for both campaigns combined
        total_sends = 0
        for camp_id in [exp.get("control_campaign_id"), exp.get("variant_campaign_id")]:
            if camp_id:
                r = (
                    sb.table("sending_schedule")
                    .select("id", count="exact")
                    .eq("campaign_id", camp_id)
                    .in_("status", ["sent", "replied", "bounced"])
                    .execute()
                )
                total_sends += r.count or 0
        pct = round(total_sends / exp["min_sample_size"] * 100) if exp.get("min_sample_size") else 0
        results.append({
            "name": exp["name"],
            "hypothesis": exp.get("hypothesis", ""),
            "metric": exp.get("metric", "reply_rate"),
            "progress_pct": min(pct, 100),
            "total_sends": total_sends,
            "min_sample": exp.get("min_sample_size", 100),
        })
    return results


def _gather_pending_decisions(sb: Client, client_id: str) -> list[dict]:
    """Return recent decision_log entries whose effect has not been calculated yet."""
    cutoff = (datetime.now(timezone.utc) - timedelta(days=14)).isoformat()
    resp = (
        sb.table("decision_log")
        .select("id, decision_type, entity_type, entity_name, reason, created_at")
        .eq("client_id", client_id)
        .is_("effect", "null")
        .gte("created_at", cutoff)
        .order("created_at", desc=True)
        .limit(5)
        .execute()
    )
    return resp.data or []


# ---------------------------------------------------------------------------
# AI focus block
# ---------------------------------------------------------------------------

def _generate_focus_block(
    inbox_data: dict,
    campaigns: list[dict],
    experiments: list[dict],
    pending_decisions: list[dict],
    supabase_client=None,
    client_id: str | None = None,
) -> str:
    """Ask Claude Sonnet for a 2–3 sentence focus recommendation in the configured language."""
    if not _ANTHROPIC_KEY:
        return ""

    lang_instruction = {
        "nl": "Schrijf in het Nederlands.",
        "en": "Write in English.",
        "fr": "Écris en français.",
    }.get(_LANGUAGE, "Schrijf in het Nederlands.")

    alerts = []
    if inbox_data["paused"] > 0:
        alerts.append(f"{inbox_data['paused']} inbox(en) gepauzeerd")
    if inbox_data["spam_complaints"] > 0:
        alerts.append(f"{inbox_data['spam_complaints']} spam klacht(en)")
    for c in campaigns:
        if c.get("alert"):
            alerts.append(f"Bounce rate te hoog op campagne '{c['name']}': {c['bounce_rate']}%")
    for exp in experiments:
        if exp["progress_pct"] >= 100:
            alerts.append(f"Experiment '{exp['name']}' heeft genoeg data — klaar voor conclusie")

    context_lines = [
        f"Inbox gezondheid: {inbox_data['total']} inboxes, gemiddelde reputatie {inbox_data['avg_reputation']}/100, {inbox_data['ready']} klaar voor campagnes.",
        "Campagnes (top): " + (', '.join(f"{c['name']} ({c['reply_rate']}% reply)" for c in campaigns[:3]) or 'geen actief') + ".",
        f"Actieve experimenten: {len(experiments)}.",
        f"Openstaande beslissingen zonder effect-meting: {len(pending_decisions)}.",
    ]
    if alerts:
        context_lines.append(f"Aandachtspunten: {'; '.join(alerts)}.")

    prompt = (
        "Je bent de AI-assistent van een email deliverability platform. "
        "Hieronder staat de huidige staat van het systeem.\n\n"
        + "\n".join(context_lines)
        + "\n\nGeef in 2 à 3 zinnen het meest belangrijke focuspunt voor vandaag. "
        "Wees concreet en actiegericht. Geen opsommingen, geen markdown. "
        + lang_instruction
    )

    try:
        client = Anthropic(api_key=_ANTHROPIC_KEY)
        messages = [{"role": "user", "content": prompt}]

        if supabase_client:
            from utils.cost_tracker import tracked_claude_call
            response = tracked_claude_call(
                client, supabase_client,
                model="claude-sonnet-4-6",
                messages=messages,
                max_tokens=200,
                context="daily_briefing",
                client_id=client_id,
            )
        else:
            response = client.messages.create(
                model="claude-sonnet-4-6",
                max_tokens=200,
                messages=messages,
            )
        return response.content[0].text.strip()
    except Exception as exc:
        logger.error("Claude focus generation failed: %s", exc)
        return ""


# ---------------------------------------------------------------------------
# HTML builder
# ---------------------------------------------------------------------------

def _rep_color(score: float) -> str:
    """Return a hex colour based on the reputation score."""
    if score >= 70:
        return "#00856d"
    if score >= 45:
        return "#e67e22"
    return "#c0392b"


def _build_html(
    client_name: str,
    inbox_data: dict,
    campaigns: list[dict],
    experiments: list[dict],
    pending_decisions: list[dict],
    focus_block: str,
) -> str:
    """Render the briefing as an HTML email string."""
    today = date.today().strftime("%d %B %Y")

    # Inbox rows
    inbox_rows_html = ""
    for inbox in sorted(inbox_data["rows"], key=lambda x: x.get("reputation_score", 0), reverse=True)[:8]:
        score = inbox.get("reputation_score", 0)
        color = _rep_color(score)
        status_label = inbox.get("status", "—")
        inbox_rows_html += f"""
        <tr>
          <td style="padding:.4rem .75rem;border-bottom:1px solid #f0eeff;font-size:.85rem">{inbox.get("email","")}</td>
          <td style="padding:.4rem .75rem;border-bottom:1px solid #f0eeff;font-size:.85rem;font-weight:700;color:{color}">{score}</td>
          <td style="padding:.4rem .75rem;border-bottom:1px solid #f0eeff;font-size:.85rem;color:#888">{status_label}</td>
        </tr>"""

    # Campaign rows
    camp_rows_html = ""
    for c in campaigns:
        alert_style = "color:#c0392b;font-weight:700" if c.get("alert") else ""
        camp_rows_html += f"""
        <tr>
          <td style="padding:.4rem .75rem;border-bottom:1px solid #f0eeff;font-size:.85rem">{c["name"]}</td>
          <td style="padding:.4rem .75rem;border-bottom:1px solid #f0eeff;font-size:.85rem;color:#00856d;font-weight:700">{c["reply_rate"]}%</td>
          <td style="padding:.4rem .75rem;border-bottom:1px solid #f0eeff;font-size:.85rem;{alert_style}">{c["bounce_rate"]}%</td>
          <td style="padding:.4rem .75rem;border-bottom:1px solid #f0eeff;font-size:.85rem;color:#888">{c["sent_7d"]} verzonden</td>
        </tr>"""
    if not camp_rows_html:
        camp_rows_html = f'<tr><td colspan="4" style="padding:.75rem;color:#888;font-size:.85rem">{_L["no_campaigns"]}</td></tr>'

    # Experiment rows
    exp_rows_html = ""
    for exp in experiments:
        pct = exp["progress_pct"]
        bar_color = "#7c5cbf" if pct < 100 else "#00856d"
        exp_rows_html += f"""
        <tr>
          <td style="padding:.4rem .75rem;border-bottom:1px solid #f0eeff;font-size:.85rem">{exp["name"]}</td>
          <td style="padding:.4rem .75rem;border-bottom:1px solid #f0eeff;font-size:.85rem">
            <div style="background:#f0eeff;border-radius:4px;height:8px;width:120px">
              <div style="background:{bar_color};border-radius:4px;height:8px;width:{pct * 1.2}px"></div>
            </div>
            <span style="font-size:.75rem;color:#888">{exp["total_sends"]}/{exp["min_sample"]} ({pct}%)</span>
          </td>
          <td style="padding:.4rem .75rem;border-bottom:1px solid #f0eeff;font-size:.85rem;color:#888">{exp["metric"]}</td>
        </tr>"""
    if not exp_rows_html:
        exp_rows_html = f'<tr><td colspan="3" style="padding:.75rem;color:#888;font-size:.85rem">{_L["no_experiments"]}</td></tr>'

    # Decision rows
    dec_rows_html = ""
    for d in pending_decisions:
        dt = d.get("created_at", "")[:10]
        dec_rows_html += f"""
        <tr>
          <td style="padding:.4rem .75rem;border-bottom:1px solid #f0eeff;font-size:.85rem">{d.get("decision_type","")}</td>
          <td style="padding:.4rem .75rem;border-bottom:1px solid #f0eeff;font-size:.85rem">{d.get("entity_name","—")}</td>
          <td style="padding:.4rem .75rem;border-bottom:1px solid #f0eeff;font-size:.85rem;color:#888">{dt}</td>
        </tr>"""
    if not dec_rows_html:
        dec_rows_html = f'<tr><td colspan="3" style="padding:.75rem;color:#888;font-size:.85rem">{_L["no_decisions"]}</td></tr>'

    # Focus block
    focus_html = ""
    if focus_block:
        focus_html = f"""
        <div style="margin:2rem 0;padding:1.25rem 1.5rem;background:linear-gradient(135deg,#7c5cbf,#a080e0);border-radius:10px;color:#fff">
          <div style="font-size:.7rem;font-weight:700;letter-spacing:.08em;text-transform:uppercase;margin-bottom:.5rem;opacity:.85">{_L["focus_section"]}</div>
          <div style="font-size:.9375rem;line-height:1.6">{focus_block}</div>
        </div>"""

    stat_boxes = f"""
        <div style="display:flex;gap:1rem;margin-bottom:2rem;flex-wrap:wrap">
          <div style="flex:1;min-width:110px;background:#f8f6ff;border-radius:10px;padding:1rem;text-align:center">
            <div style="font-size:1.75rem;font-weight:800;color:#7c5cbf">{inbox_data['total']}</div>
            <div style="font-size:.75rem;color:#888">Inboxes</div>
          </div>
          <div style="flex:1;min-width:110px;background:#f0faf6;border-radius:10px;padding:1rem;text-align:center">
            <div style="font-size:1.75rem;font-weight:800;color:#00856d">{inbox_data['ready']}</div>
            <div style="font-size:.75rem;color:#888">{_L['ready'].capitalize()}</div>
          </div>
          <div style="flex:1;min-width:110px;background:#f8f6ff;border-radius:10px;padding:1rem;text-align:center">
            <div style="font-size:1.75rem;font-weight:800;color:#7c5cbf">{inbox_data['avg_reputation']}</div>
            <div style="font-size:.75rem;color:#888">Gem. reputatie</div>
          </div>
          <div style="flex:1;min-width:110px;background:{'#fff5f5' if inbox_data['paused'] else '#f8f6ff'};border-radius:10px;padding:1rem;text-align:center">
            <div style="font-size:1.75rem;font-weight:800;color:{'#c0392b' if inbox_data['paused'] else '#7c5cbf'}">{inbox_data['paused']}</div>
            <div style="font-size:.75rem;color:#888">{_L['paused'].capitalize()}</div>
          </div>
        </div>"""

    return f"""<!DOCTYPE html>
<html lang="{_LANGUAGE}">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{_L['subject']}</title></head>
<body style="margin:0;padding:0;background:#f5f4fa;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif">
  <div style="max-width:640px;margin:2rem auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,.08)">

    <!-- Header -->
    <div style="background:linear-gradient(135deg,#7c5cbf 0%,#a080e0 100%);padding:2rem 2rem 1.5rem">
      <div style="font-size:1.5rem;font-weight:800;color:#fff;letter-spacing:-.01em">Warmr</div>
      <div style="font-size:.875rem;color:rgba(255,255,255,.8);margin-top:.25rem">{today}</div>
    </div>

    <!-- Body -->
    <div style="padding:2rem">
      <p style="font-size:1rem;color:#333;margin-bottom:1.5rem">{_L['greeting']} {client_name},</p>

      {stat_boxes}
      {focus_html}

      <!-- Inbox health -->
      <h2 style="font-size:.9375rem;font-weight:700;color:#333;margin:1.5rem 0 .75rem">{_L['inbox_section']}</h2>
      <table style="width:100%;border-collapse:collapse">
        <thead><tr style="background:#f8f6ff">
          <th style="padding:.5rem .75rem;text-align:left;font-size:.75rem;color:#888;font-weight:600">Email</th>
          <th style="padding:.5rem .75rem;text-align:left;font-size:.75rem;color:#888;font-weight:600">Score</th>
          <th style="padding:.5rem .75rem;text-align:left;font-size:.75rem;color:#888;font-weight:600">Status</th>
        </tr></thead>
        <tbody>{inbox_rows_html}</tbody>
      </table>

      <!-- Campaigns -->
      <h2 style="font-size:.9375rem;font-weight:700;color:#333;margin:1.5rem 0 .75rem">{_L['campaign_section']} (7d)</h2>
      <table style="width:100%;border-collapse:collapse">
        <thead><tr style="background:#f8f6ff">
          <th style="padding:.5rem .75rem;text-align:left;font-size:.75rem;color:#888;font-weight:600">Campagne</th>
          <th style="padding:.5rem .75rem;text-align:left;font-size:.75rem;color:#888;font-weight:600">{_L['reply_rate']}</th>
          <th style="padding:.5rem .75rem;text-align:left;font-size:.75rem;color:#888;font-weight:600">{_L['bounce_rate']}</th>
          <th style="padding:.5rem .75rem;text-align:left;font-size:.75rem;color:#888;font-weight:600">Volume</th>
        </tr></thead>
        <tbody>{camp_rows_html}</tbody>
      </table>

      <!-- Experiments -->
      <h2 style="font-size:.9375rem;font-weight:700;color:#333;margin:1.5rem 0 .75rem">{_L['experiment_section']}</h2>
      <table style="width:100%;border-collapse:collapse">
        <thead><tr style="background:#f8f6ff">
          <th style="padding:.5rem .75rem;text-align:left;font-size:.75rem;color:#888;font-weight:600">Naam</th>
          <th style="padding:.5rem .75rem;text-align:left;font-size:.75rem;color:#888;font-weight:600">{_L['progress'].capitalize()}</th>
          <th style="padding:.5rem .75rem;text-align:left;font-size:.75rem;color:#888;font-weight:600">Metric</th>
        </tr></thead>
        <tbody>{exp_rows_html}</tbody>
      </table>

      <!-- Decisions -->
      <h2 style="font-size:.9375rem;font-weight:700;color:#333;margin:1.5rem 0 .75rem">{_L['decision_section']}</h2>
      <table style="width:100%;border-collapse:collapse">
        <thead><tr style="background:#f8f6ff">
          <th style="padding:.5rem .75rem;text-align:left;font-size:.75rem;color:#888;font-weight:600">Type</th>
          <th style="padding:.5rem .75rem;text-align:left;font-size:.75rem;color:#888;font-weight:600">Entity</th>
          <th style="padding:.5rem .75rem;text-align:left;font-size:.75rem;color:#888;font-weight:600">Datum</th>
        </tr></thead>
        <tbody>{dec_rows_html}</tbody>
      </table>
    </div>

    <!-- Footer -->
    <div style="padding:1.25rem 2rem;background:#fafafa;border-top:1px solid #f0eeff;text-align:center">
      <p style="font-size:.75rem;color:#aaa;margin:0">{_L['footer']}</p>
    </div>
  </div>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Resend delivery
# ---------------------------------------------------------------------------

def _send_via_resend(to_email: str, subject: str, html: str) -> bool:
    """POST the email to the Resend API. Returns True on success."""
    if not _RESEND_KEY:
        logger.warning("RESEND_API_KEY not set — email not sent. Dry-run mode.")
        return False
    try:
        resp = httpx.post(
            "https://api.resend.com/emails",
            headers={"Authorization": f"Bearer {_RESEND_KEY}", "Content-Type": "application/json"},
            json={"from": _FROM_EMAIL, "to": [to_email], "subject": subject, "html": html},
            timeout=15,
        )
        resp.raise_for_status()
        logger.info("Briefing sent to %s (id=%s)", to_email, resp.json().get("id"))
        return True
    except Exception as exc:
        logger.error("Resend delivery failed: %s", exc)
        return False


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def generate_and_send(client_id: str, sb: Optional[Client] = None, dry_run: bool = False) -> dict:
    """
    Generate and optionally send the morning briefing for a client.

    Args:
        client_id:  Supabase user UUID.
        sb:         Optional existing Supabase client (injected by the API layer).
        dry_run:    If True, return HTML without sending email.

    Returns dict with keys: sent (bool), html (str), recipient (str).
    """
    if sb is None:
        if not _SUPABASE_URL or not _SUPABASE_KEY:
            raise RuntimeError("SUPABASE_URL and SUPABASE_KEY must be set.")
        sb = create_client(_SUPABASE_URL, _SUPABASE_KEY)

    # Look up client name + email
    client_resp = (
        sb.table("clients")
        .select("company_name, email")
        .eq("id", client_id)
        .limit(1)
        .execute()
    )
    client_row = (client_resp.data or [{}])[0]
    client_name = client_row.get("company_name") or "daar"
    to_email = os.getenv("BRIEFING_TO_EMAIL") or client_row.get("email", "")

    # Gather data
    inbox_data = _gather_inbox_data(sb, client_id)
    campaigns = _gather_campaign_data(sb, client_id)
    experiments = _gather_experiment_data(sb, client_id)
    pending_decisions = _gather_pending_decisions(sb, client_id)

    # AI focus block
    focus_block = _generate_focus_block(inbox_data, campaigns, experiments, pending_decisions)

    # Build HTML
    html = _build_html(client_name, inbox_data, campaigns, experiments, pending_decisions, focus_block)

    if dry_run:
        return {"sent": False, "html": html, "recipient": to_email}

    sent = _send_via_resend(to_email, _L["subject"], html)
    return {"sent": sent, "html": html, "recipient": to_email}


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python daily_briefing.py <client_id> [--dry-run]")
        sys.exit(1)
    cid = sys.argv[1]
    is_dry = "--dry-run" in sys.argv
    result = generate_and_send(cid, dry_run=is_dry)
    if is_dry:
        with open("/tmp/briefing_preview.html", "w") as f:
            f.write(result["html"])
        print(f"Dry-run complete. Preview written to /tmp/briefing_preview.html (recipient: {result['recipient']})")
    else:
        print(f"Sent: {result['sent']} → {result['recipient']}")
